### ISSUE TITLE
Permission typo on wiki

### ISSUE THREAD

**Issue by Pulz-TCP** [MilSpecSG/MSDataSync#12]
https://github.com/AnvilPowered/DataSync/wiki/Permissions
datatsync.lock >> datasync.lock

Throws a spanner if you copy paste like I did aha.

**Comment by alexstaeding** [comment]
Good catch, fixed by https://github.com/AnvilPowered/DataSync/wiki/Permissions/b6a23c49d0986c89acd10da04d44fabf44f3e87c
